### ISSUE TITLE
feature request: add linux/unix support

### ISSUE THREAD

**Issue by Bogdan107** [RubyLane/parse_args#2]
I want to build and use parse_args library in Linux.
Please, add support of Linux OS in build process.

**Comment by cyanogilvie** [comment]
Linux is the only platform I build on, what difficulties are you having?

**Comment by Bogdan107** [comment]
I have troubles in build process:
```
$ mkdir ~/del
$ cd ~/del
$ git clone --depth 1 https://github.com/RubyLane/parse_args
$ cd parse_args
$ autoconf    
/usr/bin/m4:aclocal.m4:5: cannot open `tclconfig/tcl.m4': No such file or directory
autom4te-2.71: error: /usr/bin/m4 failed with exit status: 1
```

I have installed tcl in:
```
/usr/include/tcl*.h
/usr/lib64/pkgconfig/tcl.pc
/usr/lib64/tcl8.6/*
/usr/lib64/libtcl8.6.so
/usr/lib64/libtclstub8.6.a
/usr/lib64/tclConfig.sh
/usr/lib64/tclooConfig.sh
```
OS: Gentoo

How to build **parse_args**?

**Comment by samirkag** [comment]
Hi @cyanogilvie I see the same issue on v0.3.3 - the folder `tclconfig` is missing. I do see it on v0.3.2, so I am using that tag for now.

**Comment by cyanogilvie** [comment]
Tclconfig missing isn't a bug, it's deliberate.  The process is to fetch
the official tclconfig sources and place it into the parse_args dir and
then build

**Comment by samirkag** [comment]
Thanks @cyanogilvie - works like a charm with that included:

```
% package require parse_args
0.3.3
% exit
```

**Comment by ColdfireMC** [comment]
> Tclconfig missing isn't a bug, it's deliberate. The process is to fetch the official tclconfig sources and place it into the parse_args dir and then build, like: wget https://core.tcl-lang.org/tclconfig/tarball/main/tclconfig.tar.gz -O - |tar xz

You can specify tclconfig as an external object, so it can be downloaded automagically from the original developers site. i.e. with svn:externals

**Comment by cyanogilvie** [comment]
Where do you do this automatic configuration?  Autoconf?  These sources are
managed in git and I would add the tclconfig repo as a submodule if it was
also in git but that is managed in fossil.

**Comment by Bogdan107** [comment]
May you add an BUILD.md file with instructions about how to build this package and how to use external package in build process?

**Comment by cyanogilvie** [comment]
I've added the github mirror of the upstream tclconfig project as a submodule, so this issue shouldn't trip people up as much now.
