### ISSUE TITLE
error after install "can't read "dir": no such variable"

### ISSUE THREAD

**Issue by ColdfireMC** [RubyLane/parse_args#3]
I installed parse_args as usual but package require calls fail. I ran the /usr/lib/parse_args0.3.3/pkgIndex.tcl script manually and the dir variable is not defined.

Is this normal? can it be fixed?

**Comment by cyanogilvie** [comment]
The dir variable is set by the package loading machinery in Tcl, you
shouldn't manually source the pkgIndex.tcl script, that isn't ever going to
work.

Is the parent directory of the install path in the $auto_path global
variable of the Tcl interpreter when you try to package require it?

What error do you get when you try to load it?

**Comment by ColdfireMC** [comment]
The usual sequence

autoconf
./configure
make
make install

Despite libraries and scripts are generated properly, the package fails to load when is invoked from any tcl script. I didn't dig further into the package loading. Is there a log or something to check?

**Comment by cyanogilvie** [comment]
Check the list of paths in the global variable auto_path in the interpreter
you're trying to load parse_args into, and compare those with the directory
it is installed into.  The install dir (the one containing the pkgIndex.tcl
file) must be a direct subdirectory of one of those paths for Tcl to be
able to find it.

And please report the error message you get when you try the package
require parse_args. Without these I have nothing to go on to help you.

**Comment by ColdfireMC** [comment]
`% set auto_path
/usr/share/tcl8.5 /usr/lib64/tcl8.5 /usr/lib64/tk8.5 /usr/share/tk8.5
`
`% package require parse_args
can't find package parse_args
`
the make install result is

` /bin/sh ./tclconfig/install-sh -c  -m 644 libparse_args0.3.3.so /usr/lib/parse_args0.3.3/libparse_args0.3.3.so
 : /usr/lib/parse_args0.3.3/libparse_args0.3.3.so
 Install pkgIndex.tcl /usr/lib/parse_args0.3.3
Installing header files in /usr/include
[aestay@casav-casaestay trunk]$ sudo make install
 /bin/sh ./tclconfig/install-sh -c  -m 644 libparse_args0.3.3.so /usr/lib/parse_args0.3.3/libparse_args0.3.3.so
 : /usr/lib/parse_args0.3.3/libparse_args0.3.3.so
 Install pkgIndex.tcl /usr/lib/parse_args0.3.3
Installing header files in /usr/include
`
Apparently libraries are not getting the correct path. Configure needs a manual path or something like that?

**Comment by ColdfireMC** [comment]
```
set auto_path [linsert $auto_path 0 /usr/lib/parse_args0.3.3]
/usr/lib/parse_args0.3.3 /usr/share/tcl8.5 /usr/lib64/tcl8.5 /usr/lib64/tk8.5 /usr/share/tk8.5
```
```
package require parse_args
couldn't load file "/usr/lib/parse_args0.3.3/@PKG_LIB_FILE8@": /usr/lib/parse_args0.3.3/@PKG_LIB_FILE8@: cannot open shared object file: No such file or directory

```
```
ls /usr/lib/parse_args0.3.3/
libparse_args0.3.3.so  pkgIndex.tcl
```

**Comment by cyanogilvie** [comment]
Tcl 8.5 is obsolete and no longer supported, the latest parse_args will
only compile against current Tcl releases. It's also very strange that your
Tcl shell doesn't have /usr/lib in the auto_path. Are you using the same
Tcl install that you passed to the --with-tcl argument to parse_args'
configure script?  Also, since the PKG_LIB_FILE8 macro wasn't substituted
into the pkgIndex.tcl file it looks like an old version of tclconfig was
used.
